services:
  redis:
    image: redis:7.4
    container_name: medical-redis
    ports:
      - "6379:6379"
    volumes:
      - "../configs/redis.conf:/usr/local/etc/redis/redis.conf:ro"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
